Update circleci Node image
https://app.circleci.com/pipelines/github/Agoric/eslint-config-jessie/40/workflows/00a2458b-c83a-4224-8f7f-c227aa937f13/jobs/38 failed with,
```
ERROR: npm is known not to run on Node.js v11.15.0
You'll need to upgrade to a newer Node.js version in order to use this
version of npm. You can find the latest version at https://nodejs.org/
```

Updating per https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/